#!/usr/bin/perl

#
# License header writer
#

use warnings;
use strict;

use constant {
    TRUE    => 1,
    FALSE   => 0,
};


open(FI, "<$ARGV[0]") or die$!;
my @d = <FI>;
close(FI);

if ($d[0] =~ /^\/\*+$/
    && $d[1] =~ /\s*\*\s*Copyright/) {
    @d = remove_license_header(@d);
}
@d = add_license_header(@d);

open(FO, ">$ARGV[0]") or die$!;
print FO @d;
close(FO);

#foreach (@d) {
#    print $_;
#}

sub remove_license_header {
    my @newd = ();
    my $header = TRUE;
    foreach (@d) {
	if (TRUE == $header && /\s*\*+\/$/) {
	    $header = FALSE;
	    next;
	}
	if (FALSE == $header) {
	    push @newd, $_;
	}
    }
    return @newd;
}


sub add_license_header {
    my $license = <<'__LICENSE__';
/******************************************************************************
 * Copyright (C) 2012, 2013, 2014
 * Younghyung Cho. <yhcting77@gmail.com>
 * All rights reserved.
 *
 * This file is part of NetMBuddy
 *
 * This program is licensed under the FreeBSD license
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation
 * are those of the authors and should not be interpreted as representing
 * official policies, either expressed or implied, of the FreeBSD Project.
 *****************************************************************************/
__LICENSE__
    my @ret = @_;
    unshift @ret, $license;
    return @ret;
}
